version: "{build}"

branches:
  only:
    - master

skip_tags: true
skip_branch_with_pr: true

max_jobs: 1

image: Visual Studio 2015

init:
  - mv c:\cygwin\bin\git.exe c:\cygwin\bin\cyg-git.exe
  - tzutil /s "Central European Standard Time"

environment:
  CYGWIN: c:\cygwin
  PATH: c:\msvcxx\bin;/bin;c:\cygwin\bin;c:\mingw\bin;C:\MinGW\msys\1.0\bin;c:\Program Files\CMake\bin;$(PATH)
  YAAL_AUTO_SANITY: 1
  TRESS_CLOCK_QUALITY_MULTIPLIER: 256
  DEFAULT_TARGET: debug
  BC_PATH: c:\msvcxx\bin\bc.exe
  CONTINUOUS_INTEGRATION_SYSTEM: appveyor

install:
  - mv c:\cygwin\bin\cyg-git.exe c:\cygwin\bin\git.exe
  - cmd: bash -c "git config core.symlinks true && git config --global core.ignorecase false && git config --global core.filemode true"
  - cmd: bash -c "git reset --hard && git checkout -fq master"
  - cmd: md c:\tmp c:\msvcxx
  - curl -fsS -o c:\tmp\windows-dev.zip https://codestation.org/download/windows-dev.zip
  - unzip -q c:\tmp\windows-dev.zip -d c:\msvcxx
  - cmd: FOR /d %%e IN ( "c:\msvcxx\windows\*" ) DO ( move "%%~e" "c:\msvcxx" )
  - echo PREFIX = "c:/msvcxx"; > local.js
  - echo SYSCONFDIR = "c:/msvcxx/etc"; >> local.js
  - echo LOCALSTATEDIR = "c:/msvcxx/var"; >> local.js
  - echo EXTRA_INCLUDE_PATH = "c:/msvcxx/include"; >> local.js
  - echo EXTRA_LIBRARY_PATH = "c:/msvcxx/lib"; >> local.js
  - echo VERBOSE = 1; >> local.js
  - echo FAST = 1; >> local.js
  - cmd: bash -c "git clone -q --branch=master https://codestation.org/repo/tress.git ../tress"
  - cmd: bash -c "sed -i -e '11d' -e '/BOOST/d' -e '/\<Boost\>/d' -e 's/${Boost_LIBRARIES}//' ../tress/CMakeLists.txt"
  - del ..\tress\src\tut_boost.cxx
  - cp local.js ../tress/
  - cinst cmake
  - C:\cygwin\setup-x86.exe -qgnNdO -l C:\cygwin\var\cache\setup -R c:\cygwin -s http://cygwin.mirror.constant.com -P sqlite3 -P bc

build_script:
  - chdir
  - type local.js
  - cmd: bash -c "make -f msvcxx.mk install"
  - cmd: bash -c "make -C ../tress/ -f msvcxx.mk"
  - cp ../tress/tressrc c:/msvcxx/etc/
  - cmd: bash -c "make -C ../tress -f tress.mk"
  - cmd: bash -c "make -f msvcxx.mk EXTRA_FLAGS=YAAL_AUTO_SANITY=1 install-release"

# Build execution time has the maximum allowed time = 60 minutes.
#  - cmd: bash -c "umask 0077 && make -C _deploy/windows clean package bundle BUILD_ID=`date +%Y%m%d%H%M%S`.codestation"

