version: "{build}"

branches:
  only:
    - master

skip_tags: true
skip_branch_with_pr: true

max_jobs: 1

image: Visual Studio 2017

init:
  - tzutil /s "Central European Standard Time"

environment:
  PATH: c:\msvcxx\bin;c:\mingw\bin;C:\MinGW\msys\1.0\bin;c:\Program Files\CMake\bin;$(PATH)
  BC_PATH: c:\msvcxx\bin\bc.exe
  CONTINUOUS_INTEGRATION_SYSTEM: appveyor

install:
  - ps: ( git config --global core.symlinks true ) ; ( git config --global core.ignorecase false ) ; ( git config --global core.filemode true )
  - ps: ( git config --global core.eol lf ) ; ( git config --global core.autocrlf false ) ; ( git config --global core.safecrlf false )
  - ps: ( git reset --hard ) -And ( git checkout -fq master )
  - ps: git clone -q --branch=master https://codestation.org/repo/tress.git ../tress
  - cmd: md c:\tmp
  - del ..\tress\src\tut_boost.cxx
  - cinst cmake
  - vcpkg integrate remove

build_script:
  - chdir
  - ps: .\make.ps1 -target install-debug -prefix c:/msvcxx -auto_setup
  - cp local.js ../tress/
  - cp ../tress/tressrc c:/msvcxx/etc/
  # Need to wrap invocation in `cmd` so stderr output will not trash the logs.
  - cmd: powershell -Command ..\tress\make.ps1 -target purge,test
  - ps: .\make.ps1 -target install-release -EXTRA_FLAGS YAAL_AUTO_SANITY=1

# Build execution time has the maximum allowed time = 60 minutes.
#  - ps: .\make.ps1 -target purge,bundle -BUILD_ID "$(Get-Date -UFormat %Y%m%d%H%M%S).codestation"

