language: C++
dist: focal
install:
  - mkdir -p ../tress
  - git -C ../tress init
  - git -C ../tress fetch https://codestation.org/repo/tress.git HEAD
  - git -C ../tress reset --hard FETCH_HEAD --
  - sudo mysql -u root < ../tress/data/mysql.sql
  - echo "local all postgres peer" | sudo tee /etc/postgresql/12/main/pg_hba.conf
  - echo "local all all md5" | sudo tee -a /etc/postgresql/12/main/pg_hba.conf
  - sudo systemctl restart postgresql
before_script:
  - sudo -u postgres psql -U postgres < ../tress/data/postgresql.sql
script:
  - umask 0077
  - export CONTINUOUS_INTEGRATION_SYSTEM="travis" TIMESTAMP=`date +%Y%m%d%H%M%S`
  - export PREFIX="${HOME}/usr" SYSCONFDIR="${HOME}/etc/conf" LOCALSTATEDIR="${HOME}/var"
  - make && make install
  - make -C _deploy/debian clean package bundle BUILD_ID="-0codestation${TIMESTAMP}"
  - test -f debian/tmp/yaal-bundle.tar && while ! lftp -e 'set xfer:timeout 4;set net:timeout 4;set net:persist-retries 1024;set net:max-retries 1024;set ftp:prefer-epsv false;set ftp:passive-mode true;put debian/tmp/yaal-bundle.tar;quit' -u "travis,${TRAVIS_FTP_PASS}" codestation.org ; do true ; done
services:
  - postgresql
  - mysql
addons:
  apt:
    packages:
      - libpcre3-dev
      - libssl-dev
      - libsqlite3-dev
      - sqlite3
      - libmysqlclient-dev
      - libpq-dev
      - postgresql-12
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
      - libncursesw5-dev
      - devscripts
      - libdistro-info-perl
      - dpkg-dev
      - fakeroot
      - debhelper
      - doxygen
      - asciidoctor
      - graphviz
      - libboost-all-dev
      - lftp
      - language-pack-pl
  postgresql: "12"
sudo: false
cache:
  ccache: true
  directories:
    - ../tress
before_cache:
  - rm -f ../tress/*tress.log
