language:  C++
cache:
  ccache: true
  directories:
    - ../tress
sudo: false
install:
  - mkdir -p ../tress
  - git -C ../tress init
  - git -C ../tress fetch https://codestation.org/repo/tress.git HEAD
  - git -C ../tress reset --hard FETCH_HEAD --
script:
  - umask 0077
  - export TIMESTAMP=`date +%Y%m%d%H%M%S`
  - export EXTRA_CXXFLAGS="-DPCRE_STUDY_EXTRA_NEEDED=0"
  - export PROC_LIMIT=4096
  - make -C _deploy/debian clean package bundle BUILD_ID="-0codestation${TIMESTAMP}"
addons:
  apt:
    packages:
      - libpcre3-dev
      - libssl-dev
      - libsqlite3-dev
      - sqlite3
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
      - libncursesw5-dev
      - devscripts
      - libdistro-info-perl
      - dpkg-dev
      - fakeroot
      - debhelper
      - doxygen
      - asciidoc
      - graphviz
      - libboost-all-dev
