language: C++
dist: xenial
install:
  - mkdir -p ../tress
  - git -C ../tress init
  - git -C ../tress fetch https://codestation.org/repo/tress.git HEAD
  - git -C ../tress reset --hard FETCH_HEAD --
  - sed -e '/DROP .* IF EXISTS/d' ../tress/data/mysql.sql > ../tress/mysql.sql
  - mysql -u root < ../tress/mysql.sql
  - psql -U postgres < ../tress/data/postgresql.sql
script:
  - umask 0077
  - export CONTINUOUS_INTEGRATION_SYSTEM="travis" TIMESTAMP=`date +%Y%m%d%H%M%S`
  - export PREFIX="${HOME}/usr" SYSCONFDIR="${HOME}/etc/conf" LOCALSTATEDIR="${HOME}/var"
  - make && make install
  - make -C _deploy/debian clean package bundle BUILD_ID="-0codestation${TIMESTAMP}"
  - lftp -e 'set xfer:timeout 10;set net:timeout 10;set net:persist-retries 10;set net:max-retries 20;set ftp:prefer-epsv false;set ftp:passive-mode true;put debian/tmp/yaal-bundle.tar;quit' -u "travis,${TRAVIS_FTP_PASS}" codestation.org
services:
  - mysql
  - postgresql
addons:
  apt:
    packages:
      - libpcre3-dev
      - libssl-dev
      - libsqlite3-dev
      - sqlite3
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
      - libncursesw5-dev
      - devscripts
      - libdistro-info-perl
      - dpkg-dev
      - fakeroot
      - debhelper
      - doxygen
      - asciidoctor
      - graphviz
      - libboost-all-dev
      - lftp
sudo: false
cache:
  ccache: true
  directories:
    - ../tress
before_cache:
  - rm -f ../tress/*tress.log
