#! /bin/sh

OS=`uname`

if [ "x${OS}" = "x" ] ; then
	echo "Cannot guess your make type."
	exit 1
fi

MAKE="make"

case "x${OS}" in
	xLinux)
	;;
	xFreeBSD|xSunOS)
		MAKE="gmake"
	;;
	*)
		echo "Your make type is a wild guess."
	;;
esac

if [ ! -f .my_make ] ; then
	echo "MAKE=${MAKE}" > .my_make
else
	if [ ${#} -lt 1 -o "x${1}" != "x-q" ] ; then
		echo "your make type already set:"
		cat .my_make
		exit 1
	fi
fi

exit 0
