#! /bin/sh

HOST_OS_TYPE=`uname`

if [ ! -z "${PREFIX}" ] ; then

	/bin/rm -f ${PREFIX}/lib/ld.so.cache

	case "${HOST_OS_TYPE}" in
		FreeBSD)
			/sbin/ldconfig -i -f ${PREFIX}/lib/ld.so.cache ${PREFIX}/lib
		;;
		Linux)
			/sbin/ldconfig -f ${PREFIX}/lib/ld.so.conf -C ${PREFIX}/lib/ld.so.cache ${PREFIX}/lib > /dev/null 2> /dev/null
		;;
		SunOS)
			/bin/crle -64 -c ${PREFIX}/lib/ls.so.conf -l ${PREFIX}/lib
		;;
		CYGWIN*)
			echo "This platform does not use link caching."
		;;
		*)
			echo "Unknown host operating system type!"
			exit 1
		;;
	esac

fi

exit 0
