#! /bin/sh

if [ -z "${DIR_ROOT}" -o -z "${DIR_BUILD}" -o -z "${HDRS}" ] ; then
	printf "%b\n" "Core settings not found!"
	exit 1
fi

umask 022

cd ${DIR_ROOT}

DIR_HEADERS="${DIR_BUILD}/yaal"

for FILE in ${HDRS}; do
	mkdir -p ${DIR_HEADERS}/`dirname ${FILE}`
	awk -f -  ${FILE} > ${DIR_HEADERS}/${FILE} << EOF
/^#\\t*include "/ {
	match(\$0, "#\\t*include");
	printf "%s", substr( \$0, RSTART, RLENGTH );
	match(\$0, "\"[a-z_./-]+");
	printf " <yaal/%s>\\n", substr(\$0, RSTART + 1, RLENGTH - 1) }
!/^#\\t*include "/
EOF
done

sed -e 's/\<PACKAGE_/YAAL_PACKAGE_/g' "${DIR_BUILD}/config.hxx" > ${DIR_HEADERS}/config.hxx

head -26 ${DIR_HEADERS}/hcore/hstreaminterface.hxx | sed -e s/hstreaminterface/yaal/ > ${DIR_HEADERS}/yaal.hxx

cat << EOF >> ${DIR_HEADERS}/yaal.hxx
#ifndef YAAL_HXX_INCLUDED
#define YAAL_HXX_INCLUDED

EOF

find ${DIR_HEADERS} ! -name 'yaal.hxx' -type f | awk '{ printf "#include <%s>\n", substr( $1, match( $1, "yaal(/[^/]*)?/[^/]*.hxx" ), 255 ) }' | sort >> ${DIR_HEADERS}/yaal.hxx

cat << EOF >> ${DIR_HEADERS}/yaal.hxx

#endif /* not YAAL_HXX_INCLUDED */

EOF

