#! /bin/sh
#
#---        `yaal' (c) 1978 by Marcin 'Amok' Konarski             ---
#
# msh - this file is integral part of `yaal' project.
#
#	i.  You may not make any changes in Copyright information.
#	ii. You must attach Copyright information to any part of every copy
#	    of this software.
#
#Copyright:
#
# You are free to use this program as is, you can redistribute binary
# package freely but:
#  1. You cannot use any part of sources of this software.
#  2. You cannot redistribute any part of sources of this software.
#  3. No reverse engineering is allowed.
#  4. If you want redistribute binary package you cannot demand any fees
#     for this software.
#     You cannot even demand cost of the carrier (CD for example).
#  5. You cannot include it to any commercial enterprise (for example
#     as a free add-on to payed software or payed newspaper).
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. Use it at your own risk.

line=`grep -s LD_LIBRARY_PATH ${HOME}/.profile ${HOME}/.bashrc ${HOME}/.bash_profile ${HOME}/.cshrc ${HOME}/.tcshrc ${HOME}/.login ${HOME}/.zshrc ${HOME}/.zlogin ${HOME}/.zshenv ${HOME}/.zsh/zlogin ${HOME}/.zsh/zshrc ${HOME}/.zsh/zshenv`
if [ "x$line" != "x" ] ; then
	printf "%b\n" "Environment have been already set."
	exit 1
fi

shell_env() {
	cat ${DIR_ROOT}/_aux/${1} | sed -e "s/{YAAL_PREFIX}/${YAAL_PREFIX}/g"
}

YAAL_PREFIX=`echo ${1} | sed -e 's/\//\\\\\//g'`

printf "%b\n" "Compilation have been finished !"
printf "%b\n" "It is need to be added several lines to your .SHELLrc file :"
printf "%b\n" "#v+"
shell_env shellrc
printf "%b\n" "#v-"
printf "%b\n" "or for C shell :"
printf "%b\n" "#v+"
shell_env shellrc.csh
printf "%b\n" "#v-"
printf "%b" "Do it now ? (yes/[no]) "
read ANSWER
if [ -f yaalrc ] ; then
	cd _aux
fi
if [ "$ANSWER" ] ; then
	if [ $ANSWER = "yes" ] ; then
		export USER=`whoami`
		export SH=`grep $USER /etc/passwd | tr \/ '\n'|tail -1`
		case "$SH" in
			sh)
				shell_env shellrc >> ${HOME}/.profile
				;;
			zsh)
				if [ -f ${HOME}/.zsh/zshrc ] ; then
					shell_env shellrc >> ${HOME}/.zsh/zshrc
				elif [ -f ${HOME}/.zshrc ] ; then
					shell_env shellrc >> ${HOME}/.zshrc
				fi
				;;
			bash)
				if [ -f ${HOME}/.bashrc -a -f .bash_profile -a !'grep "source \${HOME}/\.bashrc" .bash_profile' ] ; then
					shell_env shellrc >> ${HOME}/.bashrc
				else
					shell_env shellrc >> ${HOME}/.bash_profile
				fi
				;;
			csh)
				shell_env shellrc.csh >> ${HOME}/.cshrc
				;;
			tcsh)
				shell_env shellrc.csh >> ${HOME}/.tcshrc
				;;
		esac
	else
		printf "%b\n" "Remember to add this lines so that libraries could work properly"
	fi
else
	printf "%b\n" "Remember to add this lines so that libraries could work properly"
fi

printf "%b\n" "Environment setup process ends."

exit 0

