#!/bin/sh
#
#---        `yaal' (c) 1978 by Marcin 'Amok' Konarski             ---
#
# msh - this file is integral part of `yaal' project.
#
#	i.  You may not make any changes in Copyright information.
#	ii. You must attach Copyright information to any part of every copy
#	    of this software.
#
#Copyright:
#
# You are free to use this program as is, you can redistribute binary
# package freely but:
#  1. You cannot use any part of sources of this software.
#  2. You cannot redistribute any part of sources of this software.
#  3. No reverse engineering is allowed.
#  4. If you want redistribute binary package you cannot demand any fees
#     for this software.
#     You cannot even demand cost of the carrier (CD for example).
#  5. You cannot include it to any commercial enterprise (for example 
#     as a free add-on to payed software or payed newspaper).
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. Use it at your own risk.

line=`grep -s LD_LIBRARY_PATH ~/.profile ~/.bashrc ~/.bash_profile ~/.cshrc ~/.tcshrc ~/.login ~/.zshrc ~/.zlogin ~/.zshenv ~/.zsh/zlogin ~/.zsh/zshrc ~/.zsh/zshenv`
if [ "x$line" != "x" ] ; then
	printf "%b\n" "Environment have been already set."
	exit 1
fi

printf "%b\n" "Compilation have been finished !"
printf "%b\n" "It is need to be added seweral lines to your .SHELLrc file :"
printf "%b\n" "#v+"
printf "%b\n" "set LIBRARY_PATH=~/usr/lib"
printf "%b\n" "set C_INCLUDE_PATH=~/usr/include"
printf "%b\n" "set CPLUS_INCLUDE_PATH=~/usr/include"
printf "%b\n" "set OBJC_INCLUDE_PATH=~/usr/include"
printf "%b\n" "set LD_LIBRARY_PATH=~/usr/lib"
printf "%b\n" "#v-"
printf "%b\n" "or for C shell :"
printf "%b\n" "#v+"
printf "%b\n" "setenv LIBRARY_PATH ~/usr/lib"
printf "%b\n" "setenv C_INCLUDE_PATH ~/usr/include"
printf "%b\n" "setenv CPLUS_INCLUDE_PATH ~/usr/include"
printf "%b\n" "setenv OBJC_INCLUDE_PATH ~/usr/include"
printf "%b\n" "setenv LD_LIBRARY_PATH ~/usr/lib"
printf "%b\n" "#v-"
printf "%b" "Do it now ? (yes/[no]) "
read ANSWER
if [ -f yaalrc ] ; then
	cd _aux
fi
if [ "$ANSWER" ] ; then
	if [ $ANSWER = "yes" ] ; then
		export USER=`whoami`
		export SH=`grep $USER /etc/passwd | tr \/ '\n'|tail -1`
		case "$SH" in
			sh)
				cat shellrc >> ~/.profile
				;;
			zsh)
				if [ -f ~/.zsh/zshrc ] ; then
					cat shellrc >> ~/.zsh/zshrc
				elif [ -f ~/.zshrc ] ; then
					cat shellrc >> ~/.zshrc
				fi
				;;
			bash)
				if [ -f ~/.bashrc -a -f .bash_profile -a !'grep "source \~/\.bashrc" .bash_profile' ] ; then
					cat shellrc >> ~/.bashrc
				else
					cat shellrc >> ~/.bash_profile
				fi
				;;
			csh)
				cat shellrc.csh >> ~/.cshrc
				;;
			tcsh)
				cat shellrc.csh >> ~/.tcshrc
				;;
		esac
	else
		printf "%b\n" "Remember to add this lines so that libraries could work properly"
	fi
else
	printf "%b\n" "Remember to add this lines so that libraries could work properly"
fi
source ./shellrc 2>/dev/null
source ./shellrc.csh 2>/dev/null
if [ -f shellrc ] ; then
	cd ..
fi
printf "%b\n" "Installation process ends."

exit 0

