setenv LIBRARY_PATH {YAAL_PREFIX}/lib
setenv C_INCLUDE_PATH {YAAL_PREFIX}/include
setenv CPLUS_INCLUDE_PATH {YAAL_PREFIX}/include
setenv OBJC_INCLUDE_PATH {YAAL_PREFIX}/include
setenv LD_LIBRARY_PATH {YAAL_PREFIX}/lib
