#! /bin/sh

DIR_ROOT="${1}"

if [ ! -f "${DIR_ROOT}/_aux/commit-id" ] ; then
	echo "DIR_ROOT not set!"
	exit 1
fi

shift

COMMIT_ID="${1}"

if [ -z "${COMMIT_ID}" ] ; then
	echo "COMMIT_ID path not set!"
	exit 1
fi

shift

GITID="${@}"

if [ -z "${GITID}" ] ; then
	echo "GITID not set!"
	exit 1
fi

if [ "x${GITID}" = "xtrue" ] ; then
	exit 0
fi

NEW_COMMIT_ID=`mktemp "${COMMIT_ID}.XXXXXXXXXX"`

echo "#define COMMIT_ID \"`${DIR_ROOT}/_aux/commit-id`\"" > "${NEW_COMMIT_ID}"

if ! diff -q "${NEW_COMMIT_ID}" "${COMMIT_ID}" > /dev/null 2>&1 ; then
	mv "${NEW_COMMIT_ID}" "${COMMIT_ID}"
else
	/bin/rm "${NEW_COMMIT_ID}"
fi

