CXXFLAGS			= $(CWARNING_FLAGS) $(CXXWARNING_FLAGS) \
								$(COMPILER_OPTIMIZATION_FLAGS) $(COMPILER_DEBUG_FLAGS) \
								$(COMPILER_PATH_FLAGS) $(COMPILER_PRIME_FLAGS)
LINKER_FLAGS	= $(LINKER_PATH_FLAGS) $(LINKER_PRIME_FLAGS) $(LINKER_SPECIAL_FLAGS)
