CXXFLAGS			= $(CWARNING_FLAGS) $(CXXWARNING_FLAGS) \
								$(COMPILER_OPTIMIZATION_FLAGS) $(COMPILER_DEBUG_FLAGS) \
								$(COMPILER_PROFILING_FLAGS) $(COMPILER_COVERAGE_FLAGS) \
								$(COMPILER_PATH_FLAGS) $(COMPILER_PRIME_FLAGS)

# WARNING!! $(LINKER_PRIME_FLAGS) must be last option,
# must be immediately followed by end of line
LINKER_FLAGS	= $(LINKER_PATH_FLAGS) $(LINKER_PROFILING_FLAGS) \
								$(LINKER_COVERAGE_FLAGS) $(LINKER_PRIME_FLAGS)
